### ISSUE TITLE
Adicionar Licença no projeto

### ISSUE THREAD

**Issue by KozielGPC** [cumbucadev/cinemaempoa#114]
## Descrição
Dei uma olhada aqui e percebi que o repositório está sem licença. O certo seria adicionar uma, não?

Aqui nesse link tem algumas infos sobre qual licença usar: https://choosealicense.com/

Geralmente a mais usada é a MIT, até onde eu vi.

**Comment by guites** [comment]
Opa!! Sim, o ideal é colocarmos uma licença. Enquanto eu curto bastante a vibe da MIT, eu sinto que ela é muito utilizada pelas empresas pra "lucrar" com a mão de obra dos devs que contribuem com o seu tempo livre...

Hehe eu sei que não é o caso do cinemaempoa (afinal, o projeto não é uma biblioteca), mas acho mais interessante uma licença que impeça que o software seja distribuído de forma fechada...

Lendo o site que tu mandou (muito maneiro aliás) eu acho que o que se encaixa mais nessa direção é a [gpl-3.0](https://choosealicense.com/licenses/gpl-3.0/).

Talvez a gente possa deixar essa issue aberta um tempinho pra ver se mais alguém tem alguma consideração sobre isso?

**Comment by KozielGPC** [comment]
Pelo que vi a GPL 3.0 é uma boa pra esse caso mesmo!

Pode ser! Vamos ver se outras pessoas dão algum outro ponto de vista

**Comment by camilamaia** [comment]
+1 para [gpl-3.0](https://choosealicense.com/licenses/gpl-3.0/) também!

**Comment by camilamaia** [comment]
@KozielGPC vou pegar a issue para fazer, beleza?

**Comment by KozielGPC** [comment]
@camilamaia fechou camila!
