### ISSUE TITLE
Mudança no formato do HTML da programação quebrando o scrapping

### ISSUE THREAD

**Issue by guites** [cumbucadev/cinemaempoa#117]
Acho que no dia 31/10, o HTML da página da programação (https://www.cinematecapauloamorim.com.br/grade-semanal) sofreu uma mudança.

Até então, cada dia era identificado por uma tag `<p>` que dentro tinha uma tag `<strong>` com o dia do mês. Logo depois dessa tag `<p>`, tínhamos uma tabela listando os filmes que vão passar no dia:

```html
  <!-- Lindo, bonito, organizado --> 
  <p>
    <strong> 8 de dezembro | sexta </strong>
   </p>
    <table border="0" cellpadding="0" cellspacing="0" style="width:567px">
      <tbody>
          <tr>
              <td>14h30</td>
              <td>Sala 2</td>
              <td>Filmes em competição Festival Cinema Negro em Ação</td>
          </tr>
          <tr>
              ...
          </tr>
      </tbody>
    </table>
```

O novo formato parece ser todos os dias em uma mesma tabela, e o dia do mês é só mais uma `<tr>` em uma table gigante.

```html
    <!--- caos, violência, insensatez -->
    <table border="0" cellpadding="0" cellspacing="0" style="width:461px">
          <tbody>
              <tr>
                  <td colspan="3"><strong>31 de outubro&nbsp;| quinta</strong></td>
              </tr>
              <tr>
                  <td colspan="3">&nbsp;</td>
              </tr>
              <tr>
                  <td>14h15</td>
                  <td>PA</td>
                  <td><a href="https://www.cinematecapauloamorim.com.br/programacao/2111/megalopolis">Megal&oacute;polis</a></td>
              </tr>
              <tr>
                 ...
              </tr>
              <tr>
                 ...
              </tr>
                ...
              <tr>
                  <td colspan="3" rowspan="2">&nbsp;</td>
              </tr>
              <tr>
              </tr>
              <tr>
                  <td colspan="3"><strong>1 de novembro&nbsp;| sexta</strong></td>
              </tr>
              <tr>
                  <td colspan="3">&nbsp;</td>
              </tr>
              <tr>
                  <td>14h15</td>
                  <td>PA</td>
                  <td><a href="...">...</td>
              </tr>
```

Como o algoritmo contava com a existência das diferentes tables, o scrapping parou de funcionar.

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
Eu atualizei o método `_get_todays_features()` na classe `CinematecaPauloAmorim` para lidar com o novo formato HTML da página de programação. Agora, o código procura por uma tabela gigante contendo todos os dias e filmes, em vez de tabelas separadas para cada dia. A lógica para extrair os horários e títulos dos filmes foi ajustada para funcionar com esta nova estrutura.

I also created pull request: https://github.com/cumbucadev/cinemaempoa/pull/119


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by guites** [comment]
Parece ter sido corrigido pelo #118
