### ISSUE TITLE
Adicionar tag analytics do goat counter

### ISSUE THREAD

**Issue by guites** [cumbucadev/cinemaempoa#44]
O projeto está cadastrado em: https://cinemaempoa.goatcounter.com/ mas a tag não está sendo carregada através do código fonte.

Basta adicionar a tag 

```html
<script data-goatcounter="https://cinemaempoa.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
```

Em todas as páginas públicas do projeto.

Mais informações em: https://cinemaempoa.goatcounter.com/help/start

**Comment by fbgrigolo** [comment]
Estou assumindo essa issue

**Comment by guites** [comment]
Obrigado!!

**Comment by guites** [comment]
Eu fiz uma implementação _quick and dirty_, só colocando a tag no rodapé quando for a home page. Acho que idealmente teríamos uma forma de cadastrar em algum lugar quais URLs devem mostrar a tag.

**Comment by guites** [comment]
@fbgrigolo vou deixar essa issue disponível pra caso outro dev queira pegar. Se tu ainda tiver interesse em trabalhar nela, me avisa!
