### ISSUE TITLE
Adicionar link para a postagem original do filme na listagem da home

### ISSUE THREAD

**Issue by guites** [cumbucadev/cinemaempoa#48]
Os scrappers geram um link apontando pra página de onde o filme foi raspado. (ver por ex. <https://github.com/guites/cinemaempoa/blob/implement-flask-backend/scrapers/sala_redencao.py#L228>).

Seria legal salvar esse link no banco de dados e expor ele na listagem, pois às vezes as descrições raspadas não são completas.

![image](https://github.com/guites/cinemaempoa/assets/71985299/4dc45970-f718-4e59-9749-cb346d006359)

**Comment by LeandroAgostini** [comment]
Vou tentar fazer essa

**Comment by guites** [comment]
@LeandroAgostini eu vou deixar essa atividade disponível pra caso outro dev queira tentar. Se ainda tiver interesse em trabalhar nela, me avisa!

**Comment by guites** [comment]
Fechada no PR #88 !!! Valeu @Gpocas !
