### ISSUE TITLE
Tornar frase do link "Mais informações" mais descritiva

### ISSUE THREAD

**Issue by guites** [cumbucadev/cinemaempoa#94]
![Captura de Tela 2024-10-10 às 13 41 53](https://github.com/user-attachments/assets/bd44806b-fcc4-45cd-88bd-0c8cf219bc10)

Nos filmes da programação, mostramos um link que direciona pro site, para que o usuário possa ver a fonte da postagem de onde tiramos a informação.

O link sempre diz "Mais informações", mas o uso de frases genéricas impacta negativamente no SEO do site.

Usar algo como "Ver filme no site do cinema" ou "Ver a postagem original" talvez melhore, mas é algo que precisa ser testado.

Referência: https://developer.chrome.com/docs/lighthouse/seo/link-text?utm_source=lighthouse&utm_medium=devtools&hl=pt-br

(Problema descoberto usando o lighthouse do google: https://developer.chrome.com/docs/lighthouse/overview?hl=pt-br)

**Comment by henrygoncalvess** [comment]
Abri um [Pull Request](https://github.com/cumbucadev/cinemaempoa/pull/103) explicando passo a passo como eu fiz. Espero ter ajudado 😄 🖖.
