### ISSUE TITLE
Adicionar propriedade `height` nas imagens da programação

### ISSUE THREAD

**Issue by guites** [cumbucadev/cinemaempoa#96]
Na página inicial do site, as imagens estão sem o atributo `height`, que ajuda o navegador a calcular o espaço necessário pra renderizar a imagem enquanto ele está sendo baixada.

Atualmente a altura das imagens já está sendo calculada no backend e usada como `min-height` na `<div>` que contém a imagem. Acho que é questão de adicionar na imagem.

![Captura de Tela 2024-10-10 às 13 51 40](https://github.com/user-attachments/assets/d56af9b0-e1a6-4997-b344-30d215462902)

**Comment by KozielGPC** [comment]
Olá, tudo bem? 
Sou aluno do curso de Ciência da Computação da UTFPR e estou cursando a matéria de Software Livre, onde temos que fazer contribuições com softwares open source. 

Encontrei esse repositório e me interessei em colaborar. Como primeira atividade devemos buscar uma issue marcada como `good first issue`, e achei essa aqui interessante. Posso pegar para fazer?

**Comment by guites** [comment]
@KozielGPC que maneiro, seja bem-vindo! Pode pegar sim. Qualquer dúvida que surgir na hora de rodar o projeto é só falar.

**Comment by KozielGPC** [comment]
Show! Valeu pela colaboração!

**Comment by KozielGPC** [comment]
@guites Pull Request submetido!
